global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-kafka-pro'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_timeout: 10s

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9094']
    metrics_path: /metrics
